language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-source
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --strict --coverage-clover build/logs/clover.xml

after_script:
  - composer require satooshi/php-coveralls:dev-master
  - vendor/bin/coveralls --exclude-no-stmt

matrix:
  allow_failures:
    - php: hhvm
